spring:
  application:
    name: BuildLedger
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml


  datasource:
    url: jdbc:mysql://localhost:3306/buildLedgerSchema?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 1312
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8080

management:
  metrics:
    enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
          - health
          - metrics
      base-path: /actuator
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always

